booker/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'booker'
urlpatterns = [
    # ex: /booker/
    url(r'^$', views.index, name='index'),
    url(r'^post_reservation/$', views.post_reservation, name='post_reservation'),
    url(r'^confirm/$', views.confirm, name='confirm'),
    url(r'^admin_dashboard/$', views.admin_dashboard, name='admin_dashboard'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^calendar/$', views.calendar_view, name='calendar'),
    url(r'^calendar/eventsfeed/(?P<room_name>.+)/$', views.eventsFeed, name='eventsfeed'),
    url(r'^profile/$', views.user_profile, name='profile'),
    url(r'^groupres/$', views.groupres, name='groupres'),
    url(r'^singleres/$', views.singleres, name='singleres'),
    url(r'^create_group/$', views.create_group, name='create_group'),
    url(r'^delete_profile_info/$',views.delete_profile_info,name='delete_profile_info'),
    url(r'^groups/$',views.groups,name='groups'),
    url(r'^organizations/$',views.organizations,name='organizations'),
    url(r'^join_group_request/$',views.join_group_request,name='join_group_request'),
    url(r'^join_org/$',views.join_org,name='join_org'),
    url(r'^user/$',views.user,name='user'),
    url(r'^buildings/$',views.buildings,name='buildings'),
    url(r'^calendar/get_closest_reservation/$',views.get_closest_reservation,name='get_closest_reservation'),
    url(r'^settings/$',views.settings,name='settings'),
    url(r'^change_password/$',views.change_password,name='change_password'),
    url(r'^change_profile_picture/$',views.change_profile_picture,name='change_profile_picture'),
    url(r'^user_profiles/$',views.user_profiles,name='user_profiles'),
    url(r'^add_user_to_group/$',views.add_user_to_group,name='add_user_to_group/'),
    url(r'^add_group_admin/$',views.add_group_admin,name='add_group_admin/'),
    url(r'^organization/(?P<org_id>.+)/$', views.organization, name='organization'),
    url(r'^data_dump/(?P<org_name>.+)/(?P<num_weeks>.+)/$', views.csv_dump, name='csv_dump'),
    ]

getaroom/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import booker

from . import views

urlpatterns = [
    # getaroom.space/
    # redirects to booker app
	url(r'^$', views.home, name='home'),
    # /booker/
	url(r'^booker/', include('booker.urls')),
    url(r'^admin/', admin.site.urls),
]

booker/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

def getCurDate():
	return (datetime.datetime.now(), "Today")

def make_custom_datefield(f):
    formfield = f.formfield()
    if isinstance(f, models.DateField):
        formfield.widget.format = '%m/%d/%Y'
        formfield.widget.attrs.update({'class':'datePicker', 'readonly':'true'})
    return formfield

# Create your models here.
class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)
    # The user's first name
    first_name = models.CharField(max_length=30)
    # The user's last name
    last_name = models.CharField(max_length=30)
    # Organizations the user is a member of
    organizations = models.ManyToManyField('Organization',null=True,blank=True)
    # Groups the user is a member of
    groups = models.ManyToManyField('Group',null=True,blank=True)
    # Profile picture
    picture = models.ImageField(upload_to='booker/static/images/profile_images', blank=True)

    # Override the __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username

    def get_profile_pic_url(self):
    	if self.picture:
    		return self.picture.url[len('booker/static/'):]
    	else:
    		return None

    def get_admin_organizations(self):
    	return self.organization_set.all()

class Organization(models.Model):
	name = models.CharField(max_length=200)
	admins = models.ManyToManyField(UserProfile,null=True)
	on = models.BooleanField(default=False)

	def __str__(self):
		return self.name

class Building(models.Model):
	name = models.CharField(max_length=200)
	organization = models.ForeignKey(Organization, on_delete=models.CASCADE, null=True)
	def __str__(self):
		return self.name

class Room(models.Model):
	name = models.CharField(max_length=200)
	# nice_name = models.CharField(max_length=200)
	building = models.ForeignKey(Building, on_delete=models.CASCADE)
	capacity = models.IntegerField(default=0)
	has_projector = models.BooleanField(default=False)
	has_windows = models.BooleanField(default=False)
	has_whiteboard = models.BooleanField(default=False)

	def __str__(self):
		return self.name

	def get_name(self):
		return str(self.name)

class Group(models.Model):
	name = models.CharField(max_length=200)
	# admins of this group
	# an admin user_profile can select the groups
	# they are an admin of via .admin_of.all()
	admins = models.ManyToManyField(UserProfile, related_name="admin_of")
	nres = models.PositiveSmallIntegerField(default=20)
	# Users requesting to join this group
	# a user_profile can select the groups
	# they are requesting to join via .group_requests.all()
	member_requests = models.ManyToManyField(UserProfile, related_name="group_requests",null=True)
	# vso = models.IntegerField()

	def get_member_count(self):
		return len(self.userprofile_set.all())

	def __str__(self):
		return self.name

class Reservation(models.Model):
	group = models.ForeignKey(Group, on_delete=models.CASCADE, null=True)
	room = models.ForeignKey(Room, on_delete=models.CASCADE)
	user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True)
	description = models.TextField()
	start_time = models.DateTimeField()
	end_time = models.DateTimeField()

	def get_string(self):
		return self.user_name + ' has booked ' + self.room.name + ' for ' + self.description
	#+ ' from ' + str(start_time) + ' to ' + str(end_time)

	# def __str__(self):
	# 	return ' '.join([
	# 		self.room.name,
	# 		self.user_name,
	# 	])

booker/forms.py
from django import forms
from django.db import models
from functools import partial
from datetime import datetime
import time
from booker.models import UserProfile, Group
from django.contrib.auth.models import User


def getStarterNum():
	# This function returns the time that should b shown initially
	t = time.localtime()
	h = t.tm_hour
	toReturn = (h - 7) # Accounts for tz
	toReturn = 2 * toReturn
	if(toReturn > 4 and toReturn < 16): # Times we don't have numbers
		toReturn = 16
	if(toReturn > 47):
		toReturn = 0
	return toReturn

class RoomForm(forms.Form):
	date = forms.CharField(
		widget=forms.TextInput(attrs={'class': 'datepicker'})
	)
	
	time_choices = (
		(0, '12:00 AM'),
		(1, '12:30 AM'),
		(2, '1:00 AM'),
		(3, '1:30 AM'),
		(4, '2:00 AM'),
		(16, '8:00 AM'),
		(17, '8:30 AM'),
		(18, '9:00 AM'),
		(19, '9:30 AM'),
		(20, '10:00 AM'),
		(21, '10:30 AM'),
		(22, '11:00 AM'),
		(23, '11:30 AM'),
		(24, '12:00 PM'),
		(25, '12:30 PM'),
		(26, '1:00 PM'),
		(27, '1:30 PM'),
		(28, '2:00 PM'),
		(29, '2:30 PM'),
		(30, '3:00 PM'),
		(31, '3:30 PM'),
		(32, '4:00 PM'),
		(33, '4:30 PM'),
		(34, '5:00 PM'),
		(35, '5:30 PM'),
		(36, '6:00 PM'),
		(37, '6:30 PM'),
		(38, '7:00 PM'),
		(39, '7:30 PM'),
		(40, '8:00 PM'),
		(41, '8:30 PM'),
		(42, '9:00 PM'),
		(43, '9:30 PM'),
		(44, '10:00 PM'),
		(45, '10:30 PM'),
		(46, '11:00 PM'),
		(47, '11:30 PM'),
	)

	time = forms.ChoiceField(
		label = "What Time?",
		required = False,
		choices = time_choices,
		initial = 26
	)

	duration_choices = (
		(30, '30 Minutes'),
		(60, '1 Hour'),
		(90, '90 Minutes'),
		(120, '2 Hours'),
		(150, '2.5 Hours'),
		(180, '3 Hours')
		# ('max', 'As long as possible')
	)
	duration = forms.ChoiceField(
		label = "Duration",
		required = False,
		choices = duration_choices,
		initial = 60
	)

	capacity = forms.IntegerField(
		label = "Group Size",
		min_value = 1,
		max_value = 20,
		initial = 3
	)

	weekly = forms.BooleanField(
		label = "Make Weekly",
		required = False,
		initial = False
	)

	nmeetings = forms.IntegerField(
		label = "Number of Weeks",
		min_value = 2,
		max_value = 10,
		initial = 10,
		required = False
	)

	description = forms.CharField(
		required = False,
		initial = "",
		label = "Description",
		max_length = 200
	)

	projector = forms.BooleanField(
		required = False,
		initial = False,
		label = "Projector"
	)
	whiteboard = forms.BooleanField(
		required = False,
		initial = False,
		label = "Whiteboard"
	)
	windows = forms.BooleanField(
		required = False,
		initial = False,
		label = "Windows"
	)

	area_choices = (
		('empty', ''),
		('union', 'Old Union'),
		('lathrop', 'Lathrop')
	)
	area = forms.ChoiceField(
		label = "Where?",
		required = False,
		choices = area_choices
	)

	flexible = forms.BooleanField(
		required = False,
		initial = False,
		label = "Accept other locations?"
	)

class ReservationForm(forms.Form):
	room = forms.CharField(max_length=200)
	date = forms.CharField(max_length=200)
	time = forms.CharField(max_length=200)
	duration = forms.CharField(max_length=200)
	nmeetings = forms.CharField(max_length=200)
	description = forms.CharField(max_length=200, required=False)

class GroupReservationForm(forms.Form):
	group = forms.CharField(max_length=200)

class CalendarViewForm(forms.Form):
	building_choices = (
		('Old Union', 'Old Union'),
		('Huang', 'Huang'),
		('Main Quad', 'Main Quad')
	)

	building = forms.ChoiceField(
		label = "Choose building",
		required = True,
		choices = building_choices
	)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('first_name','last_name','picture')

class ChangePasswordForm(forms.Form):
	password = forms.CharField(
		widget=forms.PasswordInput,
		label="Old password",
		required=True
	)

	new1 = forms.CharField(
		widget=forms.PasswordInput,
		label="New password",
		required=True
	)
	
	new2 = forms.CharField(
		widget=forms.PasswordInput,
		label="Confirm new password",
		required=True
	)

class ChangeProfilePictureForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ('picture',)

booker/templates/booker/calendar.html
{% extends 'booker/base.html' %}
{% load static %}
{% block head_block %}
    <!-- Calendar css/js -->
  	<link rel="stylesheet" type="text/css" href="{% static "css/calendar.css" %} ">
    <link rel="stylesheet" type="text/css" href="{% static "js/dist/sweetalert.css" %} ">
    <link rel="stylesheet" type="text/css" href="{% static "css/swal-forms.css" %} ">
    <script src="{% static "js/calendar.js" %}"></script>
    <!-- Using Bootstrap from Twitter for forms, calendar (note, different from Bootstrap on other pages) -->
    <!-- <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.0/css/bootstrap-combined.min.css" rel="stylesheet" /> -->
    <!-- // <script class="cssdesk" src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.0/js/bootstrap.min.js" type="text/javascript"></script> -->

    <!-- Using FullCalendar for calendar feature -->
    <link href="//arshaw.com/js/fullcalendar-1.5.3/fullcalendar/fullcalendar.css" rel="stylesheet" />
    <script class="cssdesk" src="//arshaw.com/js/fullcalendar-1.5.3/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>    
    <!-- Using Moment for calendar -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js" type="text/javascript"></script>
{% endblock %}

{% block body_block %}
  <div class="container">
    <div class="row">
      <div class = "CalendarTitle">
          <form role="form" class="form-inline">  
            <div class = "TitleText"> Reservation Calendar for: 
              <select class = "dropDId" id="calview_bldg" onchange="building_submit()">
                {% for building in buildings %}
                  <option value="{{building.name}}"> {{building.name}} </option>
                {% endfor %}

              </select>
          <select class="dropDId" id="calview_room" onchange="calendar_refresh()"></select>
        </form>
        </div>
      </div>
    </div>
    <div class="cal_container">
      <div id='calendar'></div>
    </div>
  </div>

{% endblock %}

booker/templates/booker/confirm.html
{% extends 'booker/base.html' %}
{% load static %}
{% block head_block %}
    <!-- Confirm css -->
    <link rel="stylesheet" type="text/css" href="{% static "css/confirm.css" %} ">
{% endblock %}

{% block body_block %}
    <div class="container">
        {% if user.is_authenticated %}
            {% if group_search %}
                <h1>Congratulations, <span class="name">{{ user.userprofile.first_name }}</span>, <br />
                You've booked a room for group '{{group}}'!</h1>
            {% else %}
                <h1>Congratulations, <span class="name">{{ user.userprofile.first_name }}</span>, <br />
                You've booked a room!</h1>
            {% endif %}
        {% else %}
            <h1>Congratulations, you've booked a room!</h1>
        {% endif %}
        <h3>Room: <span class="location">{{room}}, {{building}}</span></h3>
        {% for res in reservations %}
            <h3>Time: <span class="time">{{res.start_time}}</span> to <span class="time">{{res.end_time.time}}</span></h3>
        {% endfor %}
        <p> Thanks for using Get-A-Room! </p>
    </div>
{% endblock %}

booker/templates/booker/index.html
{% extends 'booker/base.html' %}
{% load static %}
{% block head_block %}
  <!-- Index css/js -->
  <link rel="stylesheet" type="text/css" href="{% static "css/index.css" %} ">
  <script src="{% static "js/index.js" %}"></script>
  <script>
    function show(shown, hidden1, hidden2) {
  	 document.getElementById(shown).style.display='block';
  	 document.getElementById(hidden1).style.display='none';
  	 document.getElementById(hidden2).style.display='none';
  	 document.getElementById(hidden3).style.display='none';
  	 return false;
    }
  </script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
  <script type="text/javascript">
      $(function() {
        $('#id_date').datepicker({
          minDate: 0,
          maxDate: 6
        });
      });
  </script>     </script>
{% endblock %}

{% block body_block %}
  <div class="container">
    <ul class="nav nav-pills">
      <li class="pill active grow icon" id="time-pill">
        <a class="pill-link" data-toggle="pill" href="#time" onclick="transitionPane('time')">
          <img src="{% static "images/clock_icon.png" %}" alt="Time" />
        </a>
      </li>
      <li class="pill grow icon" id="amenities-pill">
        <a class="pill-link" data-toggle="pill" href="#amenities" onclick="transitionPane('amenities')">
          <img src="{% static "images/checkbox.png"%}" alt="Amenities" /> 
        </a>
      </li>
      <li class="pill grow icon" id="location-pill">
        <a class="pill-link" data-toggle="pill" href="#location" onclick="transitionPane('location')">
          <img src="{% static "images/location_point.png" %}" alt="Location" /> 
        </a>
      </li>
      <li class="pill">
        <label for="submit-form" id="submit" class="grow">Go!</label>
      </li>
    </ul>

    <div class="arrow" id="leftarrow">
      <a id="leftarrowlink" data-toggle="pill" href="#" onclick="transitionPane(-1)">
        <img src="{% static "images/leftarrow.png" %}" alt="Left" /> 
      </a>
    </div>
    <div class="pane-container">
      <form action="." method="post">
        {% csrf_token %}
        <div class="centered-container tab-content">
          {% if group_search %}
            <h3 style="color:#fed100;">Group: {{group}}</h3>
          {% endif %}
          <div id="time" class="tab-pane fade in active">
            <h2>Time and Duration</h2>
            <div class = "form-group">
              {{ form.date.label_tag }}
              {{ form.date }}
            </div>
            <div class = "form-group">
              {{ form.time.label_tag }}
              {{ form.time }}
            </div>
            <div class = "form-group">
              {{ form.duration.label_tag }}
              {{ form.duration }}
            </div>
            <div class = "form-group">
              {{ form.capacity.label_tag }}
              {{ form.capacity }}
            </div>
            <div class = "form-group">
              {{ form.description.label_tag }}
              {{ form.description }}
            </div>
            {% if group_search %}
              <div class = "form-group">
                {{ form.weekly.label_tag }}
                {{ form.weekly }}
              </div>
            {% endif %}
            {% if group_search %}
              <div class = "form-group">
                {{ form.nmeetings.label_tag }}
                {{ form.nmeetings }}
              </div>
            {% endif %}
          </div>
          <div id="amenities" class="tab-pane fade">
            <h2>Amenities</h2>
            <div class = "form-group">
              {{ form.projector.label_tag }}
              {{ form.projector }}
            </div>
            <div class = "form-group">
              {{ form.whiteboard.label_tag }}
              {{ form.whiteboard }}
            </div>
            <div class = "form-group">
              {{ form.windows.label_tag }}
              {{ form.windows }}
            </div>
          </div>
          <div id="location" class="tab-pane fade">
            <h2>Location</h2>
            <div class = "form-group">
              {{ form.area.label_tag }}
              {{ form.area }}
            </div>
            <div class = "form-group">
              {{ form.flexible.label_tag }}
              {{ form.flexible }}
            </div>
          </div>
        </div>
        <input type="submit" id='submit-form' class = "hidden" />
      </form>
    </div>
    <div class="arrow" id="rightarrow">
      <a id="rightarrowlink" data-toggle="pill" href="#amenities" onclick="transitionPane(1)">
        <img src="{% static "images/rightarrow.png" %}" alt="Right" /> 
      </a>
    </div>

    <!-- Uncomment below for form validation errors to appear on this page -->
    <!-- {% if form.errors %}
      {% for field in form %}
        {% for error in field.errors %}
          <div class="alert alert-error">
            <strong>{{ error|escape }}</strong>
          </div>
        {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-error">
          <strong>{{ error|escape }}</strong>
        </div>
      {% endfor %}
    {% endif %} -->

  </div>
  <script>
    addClasses();
    checkTimeValues();
    checkDurationValues();
  </script>
  {% endblock %}

booker/templates/booker/profile.html
{% extends 'booker/base.html' %}
{% load static %}
{% block head_block %}
	<!-- Profile css/js -->
	<link rel="stylesheet" type="text/css" href="{% static "css/profile.css" %} ">
	<script src="{% static "js/profile.js" %}"></script>

	

	<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/smoothness/jquery-ui.css">
{% endblock %}

{% block body_block %}
	<div class="container">
		<div class="inner-container">
			<div class= "column one-forth">
				{% if profile.picture %}
					<div class="profile-pic-container">
						<div onclick="toChangePicture()" title="click to change profile picture" class="profile-pic" style="background-image: url({% static profile_pic %});">
						</div>
					</div>
				{% else %}
					<input onclick="toChangePicture()" class="profile-pic" type="image" src="{% static "images/mag_question.png" %}" border="0" alt="Upload profile picture" />
				{% endif %}
				<h2 class="user-name">
				<a class="name-link" href=".">{{ profile.first_name }} {{ profile.last_name }}</a>
				</h2>
				<a class="user-email" href="mailto:{{profile.user.username}}" "Email">{{profile.user.username}}</a>
			</div>
			<div class="column three-fourths">
				<ul class="nav nav-tabs">
					<li class="tab{{active_tab_array.0}}"><a class="tab-link" data-toggle="tab" href="#reservations" onclick="makeContentInactive()">Reservations</a></li>
					<li class="tab{{active_tab_array.1}}"><a class="tab-link" data-toggle="tab" href="#groups" onclick="makeContentInactive()" id="dirk">Groups</a></li>
					<li class="tab{{active_tab_array.2}}"><a class="tab-link" data-toggle="tab" href="#organizations" onclick="makeContentInactive()">Organizations</a></li>
				</ul>
				<div class="tab-content">
					
					<div id="reservations" class="tab-pane fade in{{active_tab_array.0}}">
						<div class="button-bar">
							<div class="header-container">
								<h3>My Reservations</h3>
							</div>
							<a href="/booker/" class="btn">Get a Room</a>
						</div>
						{% if reservations|length == 0 %}
							<p>Your schedule looks all clear!</p>
						{% else %}
							<div id="main" class="full-list">
								<div class="list-group" id="reservation-list">
									{% for reservation in reservations %}
										<a id="reservation{{ reservation.id }}" onclick="updateActiveReservation('{{profile.id}}','{{reservation.group.name}}','reservation{{reservation.id}}')" href="#" class="list-group-item">
											<h4><span>{{ reservation.room.building.name }}</span> <span>{{ reservation.room.name }}</span></h4>
											<span class="time">{{reservation.start_time}}</span> to <span class="time">{{reservation.end_time.time}}</span>
											{% if reservation.group != None %}
												<span class="groupname">{{reservation.group.name}}</span>
											{% else %}
												<span class="groupname">{{profile.first_name}} {{profile.last_name}}</span>
											{% endif %}
											<button class="btn remove-reservation-button" id="remove-reservation-button reservation{{ reservation.id }}" onclick="removeReservation('reservation{{reservation.id}}')">
												<span class="glyphicon glyphicon-remove"></span>
											</button>
										</a>
									{% endfor %}
								</div>
							</div>
						{% endif %}
					</div>

				 	<div id="groups" class="tab-pane fade in{{active_tab_array.1}}">
				 		<div class="button-bar">
							<div class="header-container">
								<h3>My Groups</h3>
							</div>
							<button class="btn" onclick="createGroupPopup()">Create Group</button>
							<button class="btn" onclick="joinGroupPopup()">Join Group</button>
						</div>
						{% if groups|length == 0 %}
							<p>Get social and join some groups! Or start one of your own!</p>
						{% else %}
							<div id="main" class="full-list">
								<div class="list-group" id="group-list">
									{% for group in groups %}
										<a id="group{{ group.id }}" href="#" class="list-group-item">
											<h4><span>{{ group.name }}</span></h4>
											<span class="pull-right">
												{% if group in admin_groups %}
													<span class="glyphicon glyphicon-tower group-header-icon" aria-hidden="true"></span>
													<span class="glyphicon glyphicon-chevron-down group-header-icon" aria-hidden="true" onclick="updateActiveGroup('group{{group.id}}')"></span>
													<!-- {% if group.member_requests.count > 0 %}
														<span class="badge request-count right"></span>
													{% endif %} -->
												{% endif %}
												<button class="btn remove-group-button" id="remove-group-button group{{ group.id }}" onclick="removeGroup('group{{group.id}}')">
													<span class="glyphicon glyphicon-remove group-header-icon"></span>
												</button>
											</span>

											{% if group in admin_groups %}
												<div id="group-content group{{ group.id }}" class="group-content">
													<div class="divider"></div>
													<div class="group-content-item" id="group-content-reservations">
														<span class="glyphicon glyphicon-search"></span>
														<h4>Upcoming Reservations</h4>
														<button class="btn right group-content-button" onclick="toGroupRes('{{group.name}}')">Make Group Reservation</button>
														{% for reservation in group.reservation_set.all %}
															{% if forloop.counter0 < 3 %}
																<span class="group-content-blurb">{{reservation.start_time|date:"F j g:i a"}} to {{reservation.end_time.time}} @{{ reservation.room.building.name }} {{ reservation.room.name }}</span>
															{% elif forloop.counter0 == 3 %}
																<span class="group-content-blurb">and {{group.reservation_set.count|add:-3}} more...</span>
															{% endif %}
														{% endfor %}
													</div>

													<div class="divider"></div>
													<div class="group-content-item" id="group-content-members">
														<span class="glyphicon glyphicon-plus"></span>
														<h4>Members</h4>
														<!-- <button class="btn right group-content-button" onclick="requestsPopup('{{group.name}}')">Requests
														</button> -->
														<button class="btn right group-content-button" onclick="addEditMembersPopup('{{group.name}}')">Add Members
														</button>
														<!-- {% if group.member_requests.count > 0 %}
															<span class="badge request-count right">{{group.member_requests.count}}</span>
														{% endif %} -->
														<span class="group-content-blurb">Total members: {{group.userprofile_set.count}}</span>
													</div>	

													<div class="divider"></div>
													<div class="group-content-item" id="group-content-admins">
														<span class="glyphicon glyphicon-tower"></span>
														<h4>Admins</h4>
														<button class="btn right group-content-button danger" onclick="deleteGroupPopup('{{group.name}}')">DELETE
														</button>
														<button class="btn right group-content-button" onclick="addEditAdminsPopup('{{group.name}}')">Add Admins
														</button>
														{% for admin in group.admins.all %}
															{% if forloop.counter0 < 3 %}
																<span class="group-content-blurb">{{admin.first_name}} {{admin.last_name}} ({{admin.user.username}})</span>
															{% elif forloop.counter0 == 3 %}
																<span class="group-content-blurb">and {{group.admins.count|add:-3}} more...</span>
															{% endif %}
														{% endfor %}
													</div>
												</div>
											{% endif %}
										</a>
									{% endfor %}
								</div>
							</div>
						{% endif %}
					</div>

					<div id="organizations" class="tab-pane fade in{{active_tab_array.2}}">
						<div class="button-bar">
							<div class="header-container">
								<h3>My Organizations</h3>
							</div>
							<button class="btn" onclick="joinOrgPopup()">Join Organization</button>
						</div>
						{% if organizations|length == 0 %}
							<p>Uh oh, you haven't joined any organizations yet! Join an organization in order to book a reservation on its calendar.</p>
						{% else %}
							<div id="main" class="full-list">
								<div class="list-group" id="org-list">
									{% for org in organizations %}
										<a id="org{{ org.id }}" onclick="updateActiveOrg('org{{org.id}}')" href="/booker/organization/{{org.id}}/" class="list-group-item">
											<h4><span>{{ org.name }}</span></h4>
											<span class="pull-right">
												{% if org in admin_organizations %}
													<span class="glyphicon glyphicon-tower" aria-hidden="true">
													</span>
												{% endif %}
												<span class="badge">{{org.get_member_count}}</span>
												<button class="btn remove-org-button" id="remove-org-button org{{ org.id }}" onclick="removeOrg('org{{org.id}}')">
													<span class="glyphicon glyphicon-remove"></span>
												</button>
											</span>
										</a>
									{% endfor %}
								</div>
							</div>
						{% endif %}
					</div>

				</div>
			</div>
		</div>
		<form style="display:none" method="POST" action="/booker/groupres/" name="groupform" id="submit_form">
			{% csrf_token %}
			<input type="text" name="group" id="group-input" />
			<input type="submit" value="submit" />
		</form>
	</div>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>
{% endblock %}